---
- hosts: web
  gather_facts: yes
  remote_user: goto
  become: yes
  become_user: root
  become_method: sudo
  vars:
    site: tty8747.devops.srwx.net
    letsencrypts_email: tty8747@gmail.com

  tasks:

    - name: apt update
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Installing nginx
      apt:
          name=nginx
          state=present
      notify: start nginx

    - name: сreate directory /opt/acme
      file:
        path=/opt/acme
        mode=0755
        owner=root
        group=root
        state=directory
      tags:
        - create

    - name: сreate directory /srv/www
      file:
        path=/srv/www
        mode=0755
        owner=root
        group=root
        state=directory

    - name: сreate directory /srv/phpapp
      file:
        path=/srv/phpapp
        mode=0755
        owner=root
        group=root
        state=directory

    - name: сreate directory /srv/goapi
      file:
        path=/srv/goapi
        mode=0755
        owner=root
        group=root
        state=directory

    - name: Push config nginx
      template: 
        src=templates/nginxTemplate.j2
        dest=/etc/nginx/sites-available/{{ site }} 
        owner=root
        group=www-data
        mode=0644
      notify: restart nginx

    - name: rm default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: create symlink
      file: src=/etc/nginx/sites-available/{{ site }} dest=/etc/nginx/sites-enabled/{{ site }} state=link
      notify: restart nginx

    - name: force handlers
      meta: flush_handlers

    - name: Install letsencrypt
      apt: 
        name=letsencrypt
        state=latest

    - name: Create letsencrypt certificate
      shell: letsencrypt certonly -n --webroot -w /opt/acme/ -d {{ site }} -m {{ letsencrypts_email }} --agree-tos
      args:
        creates: /etc/letsencrypt/live/{{ site }}/fullchain.pem

    - name: Gen dhparam
      shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
      args:
        creates: /etc/ssl/certs/dhparam.pem
      notify: restart nginx

    - name: Push config nginx
      template: 
        src=templates/nginxSslTemplate.j2
        dest=/etc/nginx/sites-available/{{ site }} 
        owner=root
        group=www-data
        mode=0644
      notify: restart nginx

    - name: letsencrypt autoupdate
      cron:
        name: get cert
        minute: "0"
        hour: "4"
        weekday: "1"
        job: "letsencrypt renew && service nginx reload" 

    - name: Create service api
      template:
        src=templates/goapi.service.j2
        dest=/etc/systemd/system/goapi.service
      notify: reload-daemon

    - name: Installing git
      apt:
          name=git
          state=present

    - name: Clone front-html
      git:
        repo: https://github.com/tty8747/goapp.git
        dest: /srv/goapi
        clone: yes

  handlers:

    - name: restart nginx
      service: name=nginx state=restarted

    - name: reload nginx
      service: name=nginx state=reloaded

    - name: start nginx
      service: name=nginx state=started
    
    - name: reload-daemon
      command: systemctl daemon-reload
