---
- hosts: all
  gather_facts: no
  vars:
   #site: tty8747.devops.srwx.net
    site: goapp.aaaj.ru

  tasks:

    - name: Write the new ec2 instance host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ site  }} >> ~/.ssh/known_hosts"

    - name: Installing python & apt update
      raw: apt-get install -y python2.7-minimal

    - name: default python2.7
      raw: update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

    - name: Adding user
      user:
        name: goto
        groups: sudo
        shell: /bin/bash

    - name: Add ssh keys to remote host
      authorized_key:
        user: goto
        state: present
        key: "{{ lookup('file', '/home/goto/.ssh/id_rsa.pub') }}"

#   - name: change /etc/sudoers
#     lineinfile: dest=/etc/sudoers
#                 regexp='^%sudo'
#                 insertbefore=BOF
#                 line='%sudo   ALL=(ALL:ALL) NOPASSWD:ALL'

    - name: push config /etc/sudoers
      template:
        src=templates/sudoers.j2
        dest=/etc/sudoers
        owner=root
        group=root
        mode=0600
